CREATE SEQUENCE IF NOT EXISTS WORKFLOW_TRANSITION_ROLE_SEQ
START WITH 1
INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS WORKFLOW_TRANSITION_ROLE
(
    ID               BIGINT NOT NULL DEFAULT nextval('WORKFLOW_TRANSITION_ROLE_SEQ'),

    TRANSITION_ID    BIGINT NOT NULL,

    ROLE_ID          BIGINT NOT NULL,

    CREATED_BY       BIGINT,
    UPDATED_BY       BIGINT,

    CREATED_AT       TIMESTAMP,
    UPDATED_AT       TIMESTAMP,

    IS_DELETED       BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT PK_WORKFLOW_TRANSITION_ROLE
    PRIMARY KEY (ID),

    CONSTRAINT UK_TRANSITION_ROLE
    UNIQUE (TRANSITION_ID, ROLE_ID),

    CONSTRAINT FK_TRANSITION_ROLE_TRANSITION
    FOREIGN KEY (TRANSITION_ID)
    REFERENCES WORKFLOW_TRANSITION (TRANSITION_ID),

    CONSTRAINT FK_TRANSITION_ROLE_ROLE
    FOREIGN KEY (ROLE_ID)
    REFERENCES ROLES (ROLE_ID)
    );