-- ==========================================
-- Sequence : ROLE_FEATURES_SEQ
-- ==========================================

CREATE SEQUENCE IF NOT EXISTS ROLE_FEATURES_SEQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    CACHE 1;


-- ==========================================
-- Table : ROLE_FEATURES
-- ==========================================

CREATE TABLE IF NOT EXISTS ROLE_FEATURES
(
    ID              BIGINT NOT NULL DEFAULT nextval('ROLE_FEATURES_SEQ'),

    ROLE_ID         BIGINT NOT NULL,
    FEATURE_ID      BIGINT NOT NULL,

    CAN_VIEW        BOOLEAN NOT NULL DEFAULT FALSE,
    CAN_CREATE      BOOLEAN NOT NULL DEFAULT FALSE,
    CAN_UPDATE      BOOLEAN NOT NULL DEFAULT FALSE,
    CAN_DELETE      BOOLEAN NOT NULL DEFAULT FALSE,
    CAN_APPROVE     BOOLEAN NOT NULL DEFAULT FALSE,
    CAN_REJECT      BOOLEAN NOT NULL DEFAULT FALSE,
    CAN_EXPORT      BOOLEAN NOT NULL DEFAULT FALSE,

    CREATED_BY      BIGINT,
    UPDATED_BY      BIGINT,

    CREATED_AT      TIMESTAMP,
    UPDATED_AT      TIMESTAMP,

    IS_DELETED      BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT PK_ROLE_FEATURES
    PRIMARY KEY (ID),

    CONSTRAINT UK_ROLE_FEATURE
    UNIQUE (ROLE_ID, FEATURE_ID),

    CONSTRAINT FK_ROLE_FEATURE_ROLE
    FOREIGN KEY (ROLE_ID)
    REFERENCES ROLES (ROLE_ID),

    CONSTRAINT FK_ROLE_FEATURE_FEATURE
    FOREIGN KEY (FEATURE_ID)
    REFERENCES FEATURES (FEATURE_ID)
    );

CREATE INDEX IF NOT EXISTS IDX_ROLE_FEATURE_ROLE
    ON ROLE_FEATURES (ROLE_ID);

CREATE INDEX IF NOT EXISTS IDX_ROLE_FEATURE_FEATURE
    ON ROLE_FEATURES (FEATURE_ID);

CREATE INDEX IF NOT EXISTS IDX_ROLE_FEATURE_DELETED
    ON ROLE_FEATURES (IS_DELETED);