-- ==========================================
-- Sequence : ORG_UNIT_SEQ
-- ==========================================

CREATE SEQUENCE IF NOT EXISTS ORG_UNIT_SEQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    CACHE 1;


-- ==========================================
-- Table : ORGANIZATION_UNIT
-- ==========================================

CREATE TABLE IF NOT EXISTS ORGANIZATION_UNIT
(
    ORG_UNIT_ID      BIGINT NOT NULL DEFAULT nextval('ORG_UNIT_SEQ'),

    TENANT_ID        BIGINT NOT NULL,

    UNIT_CODE        VARCHAR(50) NOT NULL,
    UNIT_NAME        VARCHAR(255) NOT NULL,

    UNIT_TYPE        VARCHAR(50) NOT NULL,

    PARENT_UNIT_ID   BIGINT,

    STATUS           VARCHAR(20),

    CREATED_BY       BIGINT,
    UPDATED_BY       BIGINT,

    CREATED_AT       TIMESTAMP,
    UPDATED_AT       TIMESTAMP,

    IS_DELETED       BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT PK_ORGANIZATION_UNIT
    PRIMARY KEY (ORG_UNIT_ID),

    CONSTRAINT UK_ORGANIZATION_UNIT_CODE
    UNIQUE (UNIT_CODE),

    CONSTRAINT FK_ORG_UNIT_TENANT
    FOREIGN KEY (TENANT_ID)
    REFERENCES MAS_TENANCY (TENANT_ID),

    CONSTRAINT FK_ORG_UNIT_PARENT
    FOREIGN KEY (PARENT_UNIT_ID)
    REFERENCES ORGANIZATION_UNIT (ORG_UNIT_ID)
    );


-- ==========================================
-- Indexes
-- ==========================================

CREATE INDEX IF NOT EXISTS IDX_ORG_UNIT_TENANT
    ON ORGANIZATION_UNIT (TENANT_ID);

CREATE INDEX IF NOT EXISTS IDX_ORG_UNIT_PARENT
    ON ORGANIZATION_UNIT (PARENT_UNIT_ID);

CREATE INDEX IF NOT EXISTS IDX_ORG_UNIT_TYPE
    ON ORGANIZATION_UNIT (UNIT_TYPE);

CREATE INDEX IF NOT EXISTS IDX_ORG_UNIT_DELETED
    ON ORGANIZATION_UNIT (IS_DELETED);