CREATE SEQUENCE IF NOT EXISTS ROLE_DATA_SCOPE_SEQ
START WITH 1
INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS ROLE_DATA_SCOPE
(
    ID              BIGINT NOT NULL DEFAULT nextval('ROLE_DATA_SCOPE_SEQ'),

    ROLE_ID         BIGINT NOT NULL,

    SCOPE_TYPE      VARCHAR(50) NOT NULL,

    CREATED_BY      BIGINT,
    UPDATED_BY      BIGINT,

    CREATED_AT      TIMESTAMP,
    UPDATED_AT      TIMESTAMP,

    IS_DELETED      BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT PK_ROLE_DATA_SCOPE
    PRIMARY KEY (ID),

    CONSTRAINT UK_ROLE_DATA_SCOPE
    UNIQUE (ROLE_ID),

    CONSTRAINT FK_ROLE_DATA_SCOPE_ROLE
    FOREIGN KEY (ROLE_ID)
    REFERENCES ROLES (ROLE_ID),

    CONSTRAINT CHK_ROLE_SCOPE
    CHECK (
              SCOPE_TYPE IN (
              'SELF',
              'ORG_UNIT',
              'DISTRICT',
              'STATE',
              'ALL'
                            )
    )
    );