-- ==========================================
-- Sequence : WORKFLOW_DEFINITION_SEQ
-- ==========================================

CREATE SEQUENCE IF NOT EXISTS WORKFLOW_DEFINITION_SEQ
START WITH 1
INCREMENT BY 1;

-- ==========================================
-- Table : WORKFLOW_DEFINITION
-- ==========================================

CREATE TABLE IF NOT EXISTS WORKFLOW_DEFINITION
(
    WORKFLOW_ID      BIGINT NOT NULL DEFAULT nextval('WORKFLOW_DEFINITION_SEQ'),

    TENANT_ID        BIGINT NOT NULL,

    MODULE_CODE      VARCHAR(100) NOT NULL,

    WORKFLOW_NAME    VARCHAR(200) NOT NULL,

    STATUS           VARCHAR(20),

    CREATED_BY       BIGINT,
    UPDATED_BY       BIGINT,

    CREATED_AT       TIMESTAMP,
    UPDATED_AT       TIMESTAMP,

    IS_DELETED       BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT PK_WORKFLOW_DEFINITION
    PRIMARY KEY (WORKFLOW_ID),

    CONSTRAINT UK_WORKFLOW_TENANT_MODULE
    UNIQUE (TENANT_ID, MODULE_CODE),

    CONSTRAINT FK_WORKFLOW_TENANT
    FOREIGN KEY (TENANT_ID)
    REFERENCES MAS_TENANCY (TENANT_ID)
    );