-- V2__update_status_enum_all_tables.sql

-- =========================================================
-- FEATURES
-- =========================================================
ALTER TABLE IF EXISTS FEATURES
ALTER COLUMN STATUS TYPE VARCHAR(20);

UPDATE FEATURES
SET STATUS = UPPER(STATUS)
WHERE STATUS IS NOT NULL;

ALTER TABLE FEATURES
DROP CONSTRAINT IF EXISTS CK_FEATURES_STATUS;

ALTER TABLE FEATURES
ADD CONSTRAINT CK_FEATURES_STATUS
CHECK (STATUS IN ('ACTIVE', 'INACTIVE'));



-- =========================================================
-- ORGANIZATION_UNIT
-- =========================================================
ALTER TABLE IF EXISTS ORGANIZATION_UNIT
ALTER COLUMN STATUS TYPE VARCHAR(20);

UPDATE ORGANIZATION_UNIT
SET STATUS = UPPER(STATUS)
WHERE STATUS IS NOT NULL;

ALTER TABLE ORGANIZATION_UNIT
DROP CONSTRAINT IF EXISTS CK_ORG_UNIT_STATUS;

ALTER TABLE ORGANIZATION_UNIT
ADD CONSTRAINT CK_ORG_UNIT_STATUS
CHECK (STATUS IN ('ACTIVE', 'INACTIVE'));



-- =========================================================
-- POLICIES
-- =========================================================
ALTER TABLE IF EXISTS POLICIES
ALTER COLUMN STATUS TYPE VARCHAR(20);

UPDATE POLICIES
SET STATUS = UPPER(STATUS)
WHERE STATUS IS NOT NULL;

ALTER TABLE POLICIES
DROP CONSTRAINT IF EXISTS CK_POLICIES_STATUS;

ALTER TABLE POLICIES
ADD CONSTRAINT CK_POLICIES_STATUS
CHECK (STATUS IN ('ACTIVE', 'INACTIVE'));



-- =========================================================
-- ROLES
-- =========================================================
ALTER TABLE IF EXISTS ROLES
ALTER COLUMN STATUS TYPE VARCHAR(20);

UPDATE ROLES
SET STATUS = UPPER(STATUS)
WHERE STATUS IS NOT NULL;

ALTER TABLE ROLES
DROP CONSTRAINT IF EXISTS CK_ROLES_STATUS;

ALTER TABLE ROLES
ADD CONSTRAINT CK_ROLES_STATUS
CHECK (STATUS IN ('ACTIVE', 'INACTIVE'));



-- =========================================================
-- USERS
-- =========================================================
ALTER TABLE IF EXISTS USERS
ALTER COLUMN STATUS TYPE VARCHAR(20);

UPDATE USERS
SET STATUS = UPPER(STATUS)
WHERE STATUS IS NOT NULL;

ALTER TABLE USERS
DROP CONSTRAINT IF EXISTS CK_USERS_STATUS;

ALTER TABLE USERS
ADD CONSTRAINT CK_USERS_STATUS
CHECK (STATUS IN ('ACTIVE', 'INACTIVE'));



-- =========================================================
-- WORKFLOW_DEFINITION
-- =========================================================
ALTER TABLE IF EXISTS WORKFLOW_DEFINITION
ALTER COLUMN STATUS TYPE VARCHAR(20);

UPDATE WORKFLOW_DEFINITION
SET STATUS = UPPER(STATUS)
WHERE STATUS IS NOT NULL;

ALTER TABLE WORKFLOW_DEFINITION
DROP CONSTRAINT IF EXISTS CK_WORKFLOW_DEFINITION_STATUS;

ALTER TABLE WORKFLOW_DEFINITION
ADD CONSTRAINT CK_WORKFLOW_DEFINITION_STATUS
CHECK (STATUS IN ('ACTIVE', 'INACTIVE'));



-- =========================================================
-- WORKFLOW_STEP
-- =========================================================
ALTER TABLE IF EXISTS WORKFLOW_STEP
ALTER COLUMN STATUS TYPE VARCHAR(20);

UPDATE WORKFLOW_STEP
SET STATUS = UPPER(STATUS)
WHERE STATUS IS NOT NULL;

ALTER TABLE WORKFLOW_STEP
DROP CONSTRAINT IF EXISTS CK_WORKFLOW_STEP_STATUS;

ALTER TABLE WORKFLOW_STEP
ADD CONSTRAINT CK_WORKFLOW_STEP_STATUS
CHECK (STATUS IN ('ACTIVE', 'INACTIVE'));



-- =========================================================
-- WORKFLOW_TRANSITION
-- =========================================================
ALTER TABLE IF EXISTS WORKFLOW_TRANSITION
ALTER COLUMN STATUS TYPE VARCHAR(20);

UPDATE WORKFLOW_TRANSITION
SET STATUS = UPPER(STATUS)
WHERE STATUS IS NOT NULL;

ALTER TABLE WORKFLOW_TRANSITION
DROP CONSTRAINT IF EXISTS CK_WORKFLOW_TRANSITION_STATUS;

ALTER TABLE WORKFLOW_TRANSITION
ADD CONSTRAINT CK_WORKFLOW_TRANSITION_STATUS
CHECK (STATUS IN ('ACTIVE', 'INACTIVE'));
