-- ==========================================
-- Sequence : TENANT_FEATURES_SEQ
-- ==========================================

CREATE SEQUENCE IF NOT EXISTS TENANT_FEATURES_SEQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    CACHE 1;


-- ==========================================
-- Table : TENANT_FEATURES
-- ==========================================

CREATE TABLE IF NOT EXISTS TENANT_FEATURES
(
    ID              BIGINT NOT NULL DEFAULT nextval('TENANT_FEATURES_SEQ'),

    TENANT_ID       BIGINT NOT NULL,

    FEATURE_ID      BIGINT NOT NULL,

    IS_ENABLED      BOOLEAN NOT NULL DEFAULT TRUE,

    CREATED_BY      BIGINT,
    UPDATED_BY      BIGINT,

    CREATED_AT      TIMESTAMP,
    UPDATED_AT      TIMESTAMP,

    IS_DELETED      BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT PK_TENANT_FEATURES
    PRIMARY KEY (ID),

    CONSTRAINT UK_TENANT_FEATURE
    UNIQUE (TENANT_ID, FEATURE_ID),

    CONSTRAINT FK_TENANT_FEATURE_TENANT
    FOREIGN KEY (TENANT_ID)
    REFERENCES MAS_TENANCY (TENANT_ID),

    CONSTRAINT FK_TENANT_FEATURE_FEATURE
    FOREIGN KEY (FEATURE_ID)
    REFERENCES FEATURES (FEATURE_ID)
    );


CREATE INDEX IF NOT EXISTS IDX_TENANT_FEATURE_TENANT
    ON TENANT_FEATURES (TENANT_ID);

CREATE INDEX IF NOT EXISTS IDX_TENANT_FEATURE_FEATURE
    ON TENANT_FEATURES (FEATURE_ID);

CREATE INDEX IF NOT EXISTS IDX_TENANT_FEATURE_ENABLED
    ON TENANT_FEATURES (IS_ENABLED);

CREATE INDEX IF NOT EXISTS IDX_TENANT_FEATURE_DELETED
    ON TENANT_FEATURES (IS_DELETED);