-- ==========================================
-- Sequence : FEATURES_SEQ
-- ==========================================

CREATE SEQUENCE IF NOT EXISTS FEATURES_SEQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    CACHE 1;


-- ==========================================
-- Table : FEATURES
-- ==========================================

CREATE TABLE IF NOT EXISTS FEATURES
(
    FEATURE_ID          BIGINT NOT NULL DEFAULT nextval('FEATURES_SEQ'),

    FEATURE_CODE        VARCHAR(100) NOT NULL,
    FEATURE_NAME        VARCHAR(200) NOT NULL,

    FEATURE_TYPE        VARCHAR(20) NOT NULL,

    PARENT_FEATURE_ID   BIGINT,

    SLUG                VARCHAR(200),

    ICON                VARCHAR(100),

    DISPLAY_ORDER       INTEGER,

    STATUS              VARCHAR(20),

    CREATED_BY          BIGINT,
    UPDATED_BY          BIGINT,

    CREATED_AT          TIMESTAMP,
    UPDATED_AT          TIMESTAMP,

    IS_DELETED          BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT PK_FEATURES
    PRIMARY KEY (FEATURE_ID),

    CONSTRAINT UK_FEATURE_CODE
    UNIQUE (FEATURE_CODE),

    CONSTRAINT FK_FEATURE_PARENT
    FOREIGN KEY (PARENT_FEATURE_ID)
    REFERENCES FEATURES (FEATURE_ID)
    );

CREATE INDEX IF NOT EXISTS IDX_FEATURE_PARENT
    ON FEATURES (PARENT_FEATURE_ID);

CREATE INDEX IF NOT EXISTS IDX_FEATURE_TYPE
    ON FEATURES (FEATURE_TYPE);

CREATE INDEX IF NOT EXISTS IDX_FEATURE_SLUG
    ON FEATURES (SLUG);

CREATE INDEX IF NOT EXISTS IDX_FEATURE_DELETED
    ON FEATURES (IS_DELETED);