CREATE SEQUENCE IF NOT EXISTS WORKFLOW_TRANSITION_SEQ
START WITH 1
INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS WORKFLOW_TRANSITION
(
    TRANSITION_ID      BIGINT NOT NULL DEFAULT nextval('WORKFLOW_TRANSITION_SEQ'),

    WORKFLOW_ID        BIGINT NOT NULL,

    FROM_STATE_ID      BIGINT NOT NULL,

    TO_STATE_ID        BIGINT NOT NULL,

    ACTION_CODE        VARCHAR(100) NOT NULL,

    STATUS             VARCHAR(20),

    CREATED_BY         BIGINT,
    UPDATED_BY         BIGINT,

    CREATED_AT         TIMESTAMP,
    UPDATED_AT         TIMESTAMP,

    IS_DELETED         BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT PK_WORKFLOW_TRANSITION
    PRIMARY KEY (TRANSITION_ID),

    CONSTRAINT FK_TRANSITION_WORKFLOW
    FOREIGN KEY (WORKFLOW_ID)
    REFERENCES WORKFLOW_DEFINITION (WORKFLOW_ID),

    CONSTRAINT FK_TRANSITION_FROM_STATE
    FOREIGN KEY (FROM_STATE_ID)
    REFERENCES WORKFLOW_STEP (STEP_ID),

    CONSTRAINT FK_TRANSITION_TO_STATE
    FOREIGN KEY (TO_STATE_ID)
    REFERENCES WORKFLOW_STEP (STEP_ID)
    );