CREATE SEQUENCE IF NOT EXISTS POLICY_CONDITIONS_SEQ
START WITH 1
INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS POLICY_CONDITIONS
(
    CONDITION_ID       BIGINT NOT NULL DEFAULT nextval('POLICY_CONDITIONS_SEQ'),

    POLICY_ID          BIGINT NOT NULL,

    ATTRIBUTE_NAME     VARCHAR(255) NOT NULL,

    OPERATOR           VARCHAR(50) NOT NULL,

    ATTRIBUTE_VALUE    VARCHAR(1000) NOT NULL,

    CREATED_BY         BIGINT,
    UPDATED_BY         BIGINT,

    CREATED_AT         TIMESTAMP,
    UPDATED_AT         TIMESTAMP,

    IS_DELETED         BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT PK_POLICY_CONDITIONS
    PRIMARY KEY (CONDITION_ID),

    CONSTRAINT FK_POLICY_CONDITION_POLICY
    FOREIGN KEY (POLICY_ID)
    REFERENCES POLICIES (POLICY_ID)
    );

CREATE INDEX IF NOT EXISTS IDX_POLICY_CONDITION_POLICY
    ON POLICY_CONDITIONS(POLICY_ID);

CREATE INDEX IF NOT EXISTS IDX_POLICY_CONDITION_ATTRIBUTE
    ON POLICY_CONDITIONS(ATTRIBUTE_NAME);