CREATE SEQUENCE IF NOT EXISTS POLICIES_SEQ
START WITH 1
INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS POLICIES
(
    POLICY_ID      BIGINT NOT NULL DEFAULT nextval('POLICIES_SEQ'),

    POLICY_CODE    VARCHAR(100) NOT NULL,

    FEATURE_ID     BIGINT NOT NULL,

    EFFECT         VARCHAR(20) NOT NULL,

    PRIORITY       INTEGER NOT NULL,

    STATUS         VARCHAR(20),

    CREATED_BY     BIGINT,
    UPDATED_BY     BIGINT,

    CREATED_AT     TIMESTAMP,
    UPDATED_AT     TIMESTAMP,

    IS_DELETED     BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT PK_POLICIES
    PRIMARY KEY (POLICY_ID),

    CONSTRAINT UK_POLICY_CODE
    UNIQUE (POLICY_CODE),

    CONSTRAINT FK_POLICY_FEATURE
    FOREIGN KEY (FEATURE_ID)
    REFERENCES FEATURES (FEATURE_ID)
    );


CREATE INDEX IF NOT EXISTS IDX_POLICY_FEATURE
    ON POLICIES(FEATURE_ID);

CREATE INDEX IF NOT EXISTS IDX_POLICY_PRIORITY
    ON POLICIES(PRIORITY);