-- ==========================================
-- Sequence : USER_ROLES_SEQ
-- ==========================================

CREATE SEQUENCE IF NOT EXISTS USER_ROLES_SEQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    CACHE 1;


-- ==========================================
-- Table : USER_ROLES
-- ==========================================

CREATE TABLE IF NOT EXISTS USER_ROLES
(
    ID              BIGINT NOT NULL DEFAULT nextval('USER_ROLES_SEQ'),

    USER_ID         BIGINT NOT NULL,
    ROLE_ID         BIGINT NOT NULL,

    CREATED_BY      BIGINT,
    UPDATED_BY      BIGINT,

    CREATED_AT      TIMESTAMP,
    UPDATED_AT      TIMESTAMP,

    IS_DELETED      BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT PK_USER_ROLES
    PRIMARY KEY (ID),

    CONSTRAINT UK_USER_ROLE
    UNIQUE (USER_ID, ROLE_ID),

    CONSTRAINT FK_USER_ROLES_USER
    FOREIGN KEY (USER_ID)
    REFERENCES USERS (USER_ID),

    CONSTRAINT FK_USER_ROLES_ROLE
    FOREIGN KEY (ROLE_ID)
    REFERENCES ROLES (ROLE_ID)
    );

CREATE INDEX IF NOT EXISTS IDX_USER_ROLES_USER
    ON USER_ROLES (USER_ID);

CREATE INDEX IF NOT EXISTS IDX_USER_ROLES_ROLE
    ON USER_ROLES (ROLE_ID);

CREATE INDEX IF NOT EXISTS IDX_USER_ROLES_DELETED
    ON USER_ROLES (IS_DELETED);