CREATE SEQUENCE IF NOT EXISTS WORKFLOW_STEP_SEQ
START WITH 1
INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS WORKFLOW_STEP
(
    STEP_ID          BIGINT NOT NULL DEFAULT nextval('WORKFLOW_STEP_SEQ'),

    WORKFLOW_ID      BIGINT NOT NULL,

    STEP_CODE        VARCHAR(100) NOT NULL,

    STEP_NAME        VARCHAR(200) NOT NULL,

    STEP_ORDER       INTEGER NOT NULL,

    IS_START_STEP    BOOLEAN DEFAULT FALSE,

    IS_END_STEP      BOOLEAN DEFAULT FALSE,

    STATUS           VARCHAR(20),

    CREATED_BY       BIGINT,
    UPDATED_BY       BIGINT,

    CREATED_AT       TIMESTAMP,
    UPDATED_AT       TIMESTAMP,

    IS_DELETED       BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT PK_WORKFLOW_STEP
    PRIMARY KEY (STEP_ID),

    CONSTRAINT FK_WORKFLOW_STEP_WORKFLOW
    FOREIGN KEY (WORKFLOW_ID)
    REFERENCES WORKFLOW_DEFINITION (WORKFLOW_ID)
    );

CREATE INDEX IF NOT EXISTS IDX_WORKFLOW_STEP_WORKFLOW
    ON WORKFLOW_STEP (WORKFLOW_ID);

CREATE INDEX IF NOT EXISTS IDX_WORKFLOW_STEP_ORDER
    ON WORKFLOW_STEP (STEP_ORDER);